/**
 * i18n dictionaries for the AIGC canvas plugin.
 *
 * @module @dsh-external/dsh-aigc-canvas/client/locales
 */

export const NS = 'dsh-aigc-canvas' as const

export type AigcKey =
  // Canvas view
  | 'tabTitle'
  | 'title'
  | 'empty'
  | 'emptyHint'
  | 'prompt'
  | 'image'
  | 'video'
  | 'audio'
  | 'meta'
  | 'generatedBy'
  | 'edgeCount'
  | 'elementCount'
  | 'loadError'
  | 'disconnected'
  | 'reconnecting'
  | 'refresh'
  | 'resetView'
  | 'zoom'
  | 'zoomIn'
  | 'zoomOut'
  | 'detailClose'
  | 'detailPrompt'
  | 'detailParams'
  | 'detailPosition'
  | 'detailPath'
  | 'delete'
  | 'deleteElement'
  | 'dropHint'
  | 'uploading'
  // Settings — page chrome
  | 'settingsNav'
  | 'settingsTitle'
  | 'settingsIntro'
  | 'settingsEmpty'
  | 'settingsAdd'
  | 'settingsLoading'
  | 'settingsError'
  // Settings — provider card
  | 'row.id'
  | 'row.name'
  | 'row.endpoint'
  | 'row.apiKey'
  | 'row.instructions'
  | 'row.idPlaceholder'
  | 'row.namePlaceholder'
  | 'row.endpointPlaceholder'
  | 'row.apiKeyPlaceholder'
  | 'row.instructionsPlaceholder'
  | 'row.idHint'
  | 'row.endpointDesc'
  | 'row.apiKeyDesc'
  | 'row.instructionsDesc'
  | 'row.instructionsHint'
  | 'row.save'
  | 'row.delete'
  | 'row.deleteConfirm'
  | 'row.expand'
  | 'row.collapse'
  | 'row.create'
  | 'row.cancel'
  | 'row.init'
  | 'row.initPrompt'
  | 'row.auth'
  | 'row.authBearer'
  | 'row.authHeader'
  | 'row.authQuery'
  | 'row.authDesc'
  | 'badge.builtin'
  | 'badge.stub'
  | 'badge.real'
  | 'badge.default'

export const zh: Record<AigcKey, string> = {
  tabTitle: 'AIGC 画布',
  title: 'AIGC 画布',
  empty: '画布是空的。模型通过 aigc_http_request 调用供应商 API 生成素材,再用 aigc_canvas_place 把文件放到画布的任意位置。',
  emptyHint: '可在右侧设置页配置供应商,然后让模型开始生成。',
  prompt: '提示词',
  image: '图片',
  video: '视频',
  audio: '音频',
  meta: '元信息',
  generatedBy: '生成方式',
  edgeCount: '条连线',
  elementCount: '个元素',
  loadError: '加载画布失败',
  disconnected: '已断开,正在重连…',
  reconnecting: '正在重连…',
  refresh: '刷新',
  resetView: '重置视图',
  zoom: '缩放',
  zoomIn: '放大',
  zoomOut: '缩小',
  detailClose: '关闭',
  detailPrompt: '提示词',
  detailParams: '生成参数',
  detailPosition: '位置',
  detailPath: '文件路径',
  delete: '删除',
  deleteElement: '删除元素',
  dropHint: '拖放文件到画布',
  uploading: '上传中…',
  settingsNav: 'AIGC 画布',
  settingsTitle: 'AIGC 供应商',
  settingsIntro: '配置一个或多个 AIGC 供应商。每个供应商可独立设置名称、API 地址、密钥、鉴权方式和调用说明。模型通过 aigc_get_provider_info 读取供应商列表,用 aigc_http_request 调用 API(自动携带 endpoint 和 apiKey),生成的文件用 aigc_canvas_place 放到画布上。',
  settingsEmpty: '暂无供应商,请在下方添加。',
  settingsAdd: '+ 添加供应商',
  settingsLoading: '加载中…',
  settingsError: '错误',
  'row.id': 'ID',
  'row.name': '名称',
  'row.endpoint': 'API 地址',
  'row.apiKey': 'API Key',
  'row.instructions': '调用说明',
  'row.idPlaceholder': 'volcano / jimeng / minimax',
  'row.namePlaceholder': '显示名(如"火山引擎")',
  'row.endpointPlaceholder': 'stub://aigc-backend',
  'row.apiKeyPlaceholder': 'sk-...',
  'row.instructionsPlaceholder': '调用说明由 Agent 初始化供应商时自动撰写(点击卡片上的"初始化"按钮)...',
  'row.idHint': '小写字母、数字、连字符;必须以字母开头。作为 provider_id 传给 aigc_http_request',
  'row.endpointDesc': '供应商 API 地址。填 stub://aigc-backend 使用内置 stub(合成测试媒体,不调真实 API)',
  'row.apiKeyDesc': '供应商 API 密钥。stub 后端不需要。模型看不到密钥,由 aigc_http_request 自动附加',
  'row.instructionsDesc': 'Agent 通过 aigc_get_provider_info 工具读取此字段,决定如何调用该供应商的 API',
  'row.instructionsHint': '💡 点击卡片上的"初始化"按钮,Agent 会用 aigc_http_request 探测 API 并自动撰写调用说明',
  'row.save': '保存',
  'row.delete': '删除',
  'row.deleteConfirm': '确定删除此供应商?',
  'row.expand': '展开',
  'row.collapse': '收起',
  'row.create': '创建',
  'row.cancel': '取消',
  'row.init': '初始化',
  'row.initPrompt': '请帮我初始化 AIGC 供应商「{name}」(id: {id}):先用 aigc_get_provider_info 查看配置,再用 aigc_http_request 探测它的 API(apiKey 会自动附加,无需手动传入),最后调用 aigc_provider_set_instructions 把调用说明保存下来,方便以后直接使用。',
  'row.auth': '鉴权方式',
  'row.authBearer': 'Bearer 头',
  'row.authHeader': '自定义 Header',
  'row.authQuery': 'URL 参数',
  'row.authDesc': 'aigc_http_request 自动附加 apiKey 的方式。默认 Authorization: Bearer <key>;选择自定义 Header 或 URL 参数时需填写名称',
  'badge.builtin': '内置',
  'badge.stub': 'stub 模式',
  'badge.real': '真实 API',
  'badge.default': '默认',
}

export const en: Record<AigcKey, string> = {
  tabTitle: 'AIGC Canvas',
  title: 'AIGC Canvas',
  empty: 'Canvas is empty. The agent calls provider APIs via aigc_http_request and places the generated files anywhere on the canvas with aigc_canvas_place.',
  emptyHint: 'Configure a provider in the settings tab on the right, then ask the agent to generate something.',
  prompt: 'Prompt',
  image: 'Image',
  video: 'Video',
  audio: 'Audio',
  meta: 'Metadata',
  generatedBy: 'Generated by',
  edgeCount: 'edges',
  elementCount: 'elements',
  loadError: 'Failed to load canvas',
  disconnected: 'Disconnected, reconnecting…',
  reconnecting: 'Reconnecting…',
  refresh: 'Refresh',
  resetView: 'Reset view',
  zoom: 'Zoom',
  zoomIn: 'Zoom in',
  zoomOut: 'Zoom out',
  detailClose: 'Close',
  detailPrompt: 'Prompt',
  detailParams: 'Generation params',
  detailPosition: 'Position',
  detailPath: 'File path',
  delete: 'Delete',
  deleteElement: 'Delete element',
  dropHint: 'Drop files onto canvas',
  uploading: 'Uploading…',
  settingsNav: 'AIGC Canvas',
  settingsTitle: 'AIGC Providers',
  settingsIntro: 'Configure one or more AIGC providers. Each provider has its own name, API endpoint, key, auth scheme, and usage instructions. The agent reads the provider list via aigc_get_provider_info, calls the API via aigc_http_request (endpoint + apiKey attached automatically), and places generated files onto the canvas with aigc_canvas_place.',
  settingsEmpty: 'No providers configured. Add one below.',
  settingsAdd: '+ Add provider',
  settingsLoading: 'Loading…',
  settingsError: 'Error',
  'row.id': 'ID',
  'row.name': 'Name',
  'row.endpoint': 'Endpoint',
  'row.apiKey': 'API Key',
  'row.instructions': 'Instructions',
  'row.idPlaceholder': 'volcano / jimeng / minimax',
  'row.namePlaceholder': 'Display name (e.g. "Volcano Engine")',
  'row.endpointPlaceholder': 'stub://aigc-backend',
  'row.apiKeyPlaceholder': 'sk-...',
  'row.instructionsPlaceholder': 'The agent writes these when you initialize the provider (click "Initialize" on the card)...',
  'row.idHint': 'Lowercase letters, digits, hyphens; must start with a letter. Used as the provider_id parameter to aigc_http_request',
  'row.endpointDesc': 'Provider API URL. Use stub://aigc-backend for the built-in stub (synthetic test media, no real API calls)',
  'row.apiKeyDesc': 'Provider API key. Not needed for the stub backend. The agent never sees it — aigc_http_request attaches it automatically',
  'row.instructionsDesc': 'The agent reads this field via the aigc_get_provider_info tool to decide how to call the provider API',
  'row.instructionsHint': '💡 Click "Initialize" on the card: the agent probes the API with aigc_http_request and writes the instructions itself',
  'row.save': 'Save',
  'row.delete': 'Delete',
  'row.deleteConfirm': 'Delete this provider?',
  'row.expand': 'Expand',
  'row.collapse': 'Collapse',
  'row.create': 'Create',
  'row.cancel': 'Cancel',
  'row.init': 'Initialize',
  'row.initPrompt': 'Please initialize the AIGC provider "{name}" (id: {id}): first call aigc_get_provider_info to see its config, then probe its API with aigc_http_request (the apiKey is attached automatically — do not pass it yourself), and finally call aigc_provider_set_instructions to save the usage instructions so it can be used directly later.',
  'row.auth': 'Auth scheme',
  'row.authBearer': 'Bearer header',
  'row.authHeader': 'Custom header',
  'row.authQuery': 'URL query param',
  'row.authDesc': 'How aigc_http_request attaches the apiKey. Default: Authorization: Bearer <key>. For custom header or URL query param, fill in the name',
  'badge.builtin': 'builtin',
  'badge.stub': 'stub mode',
  'badge.real': 'real API',
  'badge.default': 'default',
}
